baseURL = "https://leylatheunissen.github.io/scholarsearch-landing-page/"
languageCode = "en-us"
title = "ScholarSearch"
theme = "hugo-bootstrap-theme"

[params]
  description = "A Chrome extension to find and rank academic papers by relevance."
  favicon = "/images/favicon.ico"
  showAuthor = false
  showDate = false
  showReadingTime = false

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "Install"
  url = "/install/"
  weight = 2
[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 3